config/routes.rb
Rails.application.routes.draw do
  root :to => "visitors#index"
  devise_for :users
  resources :users

  resources :reservation_weeks do
    get 'pick', on: :collection
  end

  resources :reservations do
    get 'pick', on: :collection
    post 'lookup', on: :collection
  end

  resources :pages

  get 'contact' => 'pages#contact'
  get 'guest' => 'pages#guest'
  get 'library' => 'pages#library'
  get 'membership' => 'pages#membership'
  get 'notes' =>  'pages#note'
  get 'race' => 'pages#race'
  get 'social'=> 'pages#social'
  get 'pages' => 'pages#index'

  resources :public_pins
end

app/models/reservation_week.rb
class ReservationWeek < ActiveRecord::Base
	has_many :reservations
  has_many :users, :through => :reservations

  validates :res_date,  presence: true, uniqueness: true, :on => :create
end

app/controllers/reservation_weeks_controller.rb
class ReservationWeeksController < ApplicationController
  before_action :set_reservation_week, only: [:show, :edit, :update, :destroy]

  before_filter :require_login

  # GET /reservation_weeks
  # GET /reservation_weeks.json
  def index
    @reservation_weeks = ReservationWeek.all
  end

  # GET /reservation_weeks/1
  # GET /reservation_weeks/1.json
  def show
  end

  def pick
    @reservation_weeks = ReservationWeek.all.where("res_date >= ?", Date.today).order("res_date ASC")
  end

  # GET /reservation_weeks/new
  def new
    @reservation_week = ReservationWeek.new
  end

  # GET /reservation_weeks/1/edit
  def edit
  end

  # POST /reservation_weeks
  # POST /reservation_weeks.json
  def create
    if !find_reservation_week_detail.nil?
      respond_to do |format|
        format.html { redirect_to edit_reservation_week_path(@reservation_week) }
      end
    else
      @reservation_week = ReservationWeek.new(reservation_week_params)
      respond_to do |format|
        if @reservation_week.save
          format.html { redirect_to @reservation_week, notice: 'Reservation week was successfully created.' }
          format.json { render action: 'show', status: :created, location: @reservation_week }
        else
          format.html { render action: 'new' }
          format.json { render json: @reservation_week.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /reservation_weeks/1
  # PATCH/PUT /reservation_weeks/1.json
  def update
    respond_to do |format|
      if @reservation_week.update(reservation_week_params)
        format.html { redirect_to @reservation_week, notice: 'Reservation week was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @reservation_week.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservation_weeks/1
  # DELETE /reservation_weeks/1.json
  def destroy
    @reservation_week.destroy
    respond_to do |format|
      format.html { redirect_to reservation_weeks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation_week
      @reservation_week = ReservationWeek.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_week_params
      params.require(:reservation_week).permit(:res_date, :note)
    end

    def find_reservation_week_detail
      @reservation_week = ReservationWeek.find_by_res_date(reservation_week_params[:res_date])
      @reservation_week
    end

    def require_login
      unless current_user
        redirect_to new_user_session_url
      end
    end
end

app/views/reservation_weeks/_form.html.erb
<%= simple_form_for(@reservation_week) do |f| %>
  <% if @reservation_week.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation_week.errors.count, "error") %> prohibited this reservation note from being saved:</h2>

      <ul>
      <% @reservation_week.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="fl">
      <div class="panel panel-default">
        <div class="panel-body">
          <div id="reportrange" class="pull-right">
            <i class="fa fa-calendar fa-lg"></i>
            <% if @reservation_week.res_date.nil? %>
               <span>Pick A Reservation Week</span> <b class="caret"></b>
            <% else %>
              <span><%= l(@reservation_week.res_date, format: :notime) %> - <%= l(@reservation_week.res_date + 7.days, format: :notime) %></span> <b class="caret"></b>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= f.input :res_date , as: :hidden%>
  <%= f.input :note, as: :bootsy %>
  <%= f.button :submit, 'Save Reservation Note', class: 'btn btn-primary' %>
<% end %>
<script type="text/javascript">
var a = moment().day("Wednessday").week(Number).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 6).format('MMMM D, YYYY').toString();
var b = moment().day("Wednessday").week(Number).add('days', 7).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 13).format('MMMM D, YYYY').toString();
var c = moment().day("Wednessday").week(Number).add('days', 14).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 20).format('MMMM D, YYYY').toString();
var d = moment().day("Wednessday").week(Number).add('days',21 ).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 27).format('MMMM D, YYYY').toString();
var e = moment().day("Wednessday").week(Number).add('days',28 ).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 34).format('MMMM D, YYYY').toString();
var f = moment().day("Wednessday").week(Number).add('days', 35 ).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 41).format('MMMM D, YYYY').toString();
var g = moment().day("Wednessday").week(Number).add('days', 42 ).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 48).format('MMMM D, YYYY').toString();
var h = moment().day("Wednessday").week(Number).add('days', 49 ).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 55).format('MMMM D, YYYY').toString();
var obj = {};
obj[a] = [moment().day("Wednessday").week(Number), moment().day("Wednessday").week(Number).add('days', 6)];
obj[b] = [moment().day("Wednessday").week(Number).add('days', 7), moment().day("Wednessday").week(Number).add('days', 13)];
obj[c] = [moment().day("Wednessday").week(Number).add('days', 14), moment().day("Wednessday").week(Number).add('days', 20)];
obj[d] = [moment().day("Wednessday").week(Number).add('days',21 ), moment().day("Wednessday").week(Number).add('days', 27)];
obj[e] = [moment().day("Wednessday").week(Number).add('days',28 ), moment().day("Wednessday").week(Number).add('days', 34)];
obj[f] = [moment().day("Wednessday").week(Number).add('days', 35 ), moment().day("Wednessday").week(Number).add('days', 41)];
obj[g] = [moment().day("Wednessday").week(Number).add('days', 42 ), moment().day("Wednessday").week(Number).add('days', 48)];
obj[h] = [moment().day("Wednessday").week(Number).add('days', 49 ), moment().day("Wednessday").week(Number).add('days', 55)];
$('#reportrange').daterangepicker(
    {
      ranges: obj,
      startDate: moment().subtract('days', 29),
      endDate: moment()
    },
    function(start, end) {
        $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
        $('#reservation_week_res_date').val(start.format('"YYYY/MM/DD"'));
    }
);
</script>

app/views/reservation_weeks/edit.html.erb
<h1>Editing reservation_week</h1>
<div class="box panel panel-default">
   <div class="panel panel-body">
		<%= render 'form' %>
	</div>
</div>
<%= link_to 'Show', @reservation_week %> |
<%= link_to 'Back', reservation_weeks_path %>

app/views/reservation_weeks/index.html.erb
<div>
  <h1>Reservation Notes</h1>
</div>
<div id="res" class="transitions-enabled">
  <div class="box panel panel-default">
    <div class="panel panel-body">
      <div class="action">
        <%= link_to new_reservation_week_path do %>
          <button class="btn btn-default btn-lg" >
            <span class="glyphicon glyphicon-plus"></span> Add
          </button>
        <% end %>
      </div>
    </div>
  </div>
  <div class="box panel panel-default">
    <div class="panel panel-body">
      <div class="action">
          <%= link_to pick_reservation_weeks_path do %>
            <button class="btn btn-default btn-lg" >
              <span class="glyphicon glyphicon-pencil"></span>Edit
            </button>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reservation_weeks/new.html.erb
<h1>Create Reservation Note</h1>
<div class="box panel panel-default">
   <div class="panel panel-body">
		<%= render 'form' %>
	</div>
</div>

<%= link_to 'Back', reservation_weeks_path %>

app/views/reservation_weeks/pick.html.erb
<h1>Edit Reservation Note</h1>
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Reservation Date</th>
        <th>Note</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @reservation_weeks.each do |reservation_week| %>
        <tr>
          <td><%= l(reservation_week.res_date, format: :notime) %> - <%= l(reservation_week.res_date + 7.days, format: :notime) %></td>
          <td><%= reservation_week.note %></td>
          <td>
            <%= link_to edit_reservation_week_path(reservation_week) do %>
            <span class="glyphicon glyphicon-edit"></span>
            Edit
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'Create a New Reservation Note', new_reservation_week_path %>

app/views/reservation_weeks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Res date:</strong>
  <%= @reservation_week.res_date %>
</p>

<p>
  <strong>Note:</strong>
  <%= @reservation_week.note %>
</p>

<%= link_to 'Edit', edit_reservation_week_path(@reservation_week) %> |
<%= link_to 'Back', reservation_weeks_path %>