config/routes.rb
Rails.application.routes.draw do
  root :to => "visitors#index"
  devise_for :users
  resources :users

  resources :reservation_weeks do
    get 'pick', on: :collection
  end

  resources :reservations do
    get 'pick', on: :collection
    post 'lookup', on: :collection
  end

  resources :pages

  get 'contact' => 'pages#contact'
  get 'guest' => 'pages#guest'
  get 'library' => 'pages#library'
  get 'membership' => 'pages#membership'
  get 'notes' =>  'pages#note'
  get 'race' => 'pages#race'
  get 'social'=> 'pages#social'
  get 'pages' => 'pages#index'

  resources :public_pins
end

app/views/pages/_form.html.erb
<%= simple_form_for @page do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :title %>
  <%= f.input :text, as: :bootsy %>
  <%= f.button :submit, 'Save Page', class: 'btn btn-primary' %>
<% end %>

app/views/pages/_page_output.html.erb
<div id="pages" >
  <div class="box panel panel-default">
    <div class="panel panel-body">
      <p><%= @page.text.html_safe %></p>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<p>stuff</p>

app/views/pages/edit.html.erb
<h1>Pages#edit</h1>
<div class="box panel panel-default">
   <div class="panel panel-body">
		<%= render 'form' %>
	</div>
</div>

app/views/pages/guest.html.erb
<%= render 'page_output' %>

app/views/pages/index.html.erb
<h1>Created Pages</h1>
<div id="pages" >
  <% @pages.each do |page| %>
    <div class="box panel panel-default">
      <h2><%= page.title %></h2>
      <div class="panel panel-body">
        <p><%= page.text.html_safe %></p>
          <div class="action">
            <%= link_to edit_page_path(page) do %>
              <span class="glyphicon glyphicon-edit"></span> Edit
            <% end %>
            <%= link_to page, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span> Delete
            <% end %>
         </div>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/library.html.erb
<h1>Library</h1>
<p>library stuff</p>

app/views/pages/membership.html.erb
<%= render 'page_output' %>

app/views/pages/new.html.erb
<h1>Create Page</h1>
<div class="box panel panel-default">
   <div class="panel panel-body">
		<%= render 'form' %>
	</div>
</div>

<%= link_to 'Back', pages_path %>

app/views/pages/note.html.erb
<h1>Notes</h1>
<p>Note stuff</p>

app/views/pages/old_home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<div class="fl">
  <div class="panel panel-default">
    <div class="panel-body">
      <div id="reportrange" class="pull-right">
        <i class="fa fa-calendar fa-lg"></i>
        <span>Pick A Reservation Week</span> <b class="caret"></b>
      </div>
    </div>
  </div>
</div>



<script type="text/javascript">
var a = moment().day("Wednessday").week(Number).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 6).format('MMMM D, YYYY').toString();
var b = moment().day("Wednessday").week(Number).add('days', 7).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 13).format('MMMM D, YYYY').toString();
var c = moment().day("Wednessday").week(Number).add('days', 14).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 20).format('MMMM D, YYYY').toString();
var d = moment().day("Wednessday").week(Number).add('days',21 ).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 27).format('MMMM D, YYYY').toString();
var e = moment().day("Wednessday").week(Number).add('days',28 ).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 34).format('MMMM D, YYYY').toString();
var f = moment().day("Wednessday").week(Number).add('days', 35 ).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 41).format('MMMM D, YYYY').toString();
var g = moment().day("Wednessday").week(Number).add('days', 42 ).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 48).format('MMMM D, YYYY').toString();
var h = moment().day("Wednessday").week(Number).add('days', 49 ).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 55).format('MMMM D, YYYY').toString();
var obj = {};
obj[a] = [moment().day("Wednessday").week(Number), moment().day("Wednessday").week(Number).add('days', 6)];
obj[b] = [moment().day("Wednessday").week(Number).add('days', 7), moment().day("Wednessday").week(Number).add('days', 13)];
obj[c] = [moment().day("Wednessday").week(Number).add('days', 14), moment().day("Wednessday").week(Number).add('days', 20)];
obj[d] = [moment().day("Wednessday").week(Number).add('days',21 ), moment().day("Wednessday").week(Number).add('days', 27)];
obj[e] = [moment().day("Wednessday").week(Number).add('days',28 ), moment().day("Wednessday").week(Number).add('days', 34)];
obj[f] = [moment().day("Wednessday").week(Number).add('days', 35 ), moment().day("Wednessday").week(Number).add('days', 41)];
obj[g] = [moment().day("Wednessday").week(Number).add('days', 42 ), moment().day("Wednessday").week(Number).add('days', 48)];
obj[h] = [moment().day("Wednessday").week(Number).add('days', 49 ), moment().day("Wednessday").week(Number).add('days', 55)];
$('#reportrange').daterangepicker(
    {
      ranges: obj,
      startDate: moment().subtract('days', 29),
      endDate: moment()
    },
    function(start, end) {
        $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
    }
);
</script>

app/views/pages/show.html.erb
<h1>Created Page</h1>
<div id="pages" >
  <div class="box panel panel-default">
    <h2><%= @page.title %></h2>
    <div class="panel panel-body">
      <p><%= @page.text.html_safe %></p>
        <div class="action">
          <%= link_to edit_page_path(@page) do %>
            <span class="glyphicon glyphicon-edit"></span> Edit
          <% end %>
          <%= link_to @page, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-trash"></span> Delete
          <% end %>
       </div>
    </div>
  </div>
</div>

app/views/pages/social.html.erb
<%= render 'page_output' %>