config/routes.rb
Rails.application.routes.draw do
  root :to => "visitors#index"
  devise_for :users
  resources :users

  resources :reservation_weeks do
    get 'pick', on: :collection
  end

  resources :reservations do
    get 'pick', on: :collection
    post 'lookup', on: :collection
  end

  resources :pages

  get 'contact' => 'pages#contact'
  get 'guest' => 'pages#guest'
  get 'library' => 'pages#library'
  get 'membership' => 'pages#membership'
  get 'notes' =>  'pages#note'
  get 'race' => 'pages#race'
  get 'social'=> 'pages#social'
  get 'pages' => 'pages#index'

  resources :public_pins
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :user
  belongs_to :reservation_week

  validates :reservation_date, :name, :sex, :res_member_type,  presence: true
  validate :res_date_cannot_be_in_the_past

  def res_date_cannot_be_in_the_past
  	errors.add(:reservation_date, 'Reservations for the week are closed! You can not Edit or Save!') if reservation_date < Date.today
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  before_filter :require_login

  # GET /reservations
  def index
    @reservations = Reservation.first
  end

  def pick
    #@reservations = Reservation.all
    @reservations = current_user.reservations.where("reservation_date >= ?", Date.today).order("reservation_date ASC")
  end

  def lookup
    @reservations = Reservation.all.where("reservation_date = ?", reservation_params[:reservation_date]).order("id ASC")
    get_reservation_week_detail
  end

  # GET /reservations/1
  def show
  end

  # GET /reservations/new
  def new
    @reservation = current_user.reservations.build
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  def create
    @reservation = current_user.reservations.build(reservation_params)
    if !reservation_params[:reservation_date].empty?
      @reservation.reservation_week_id = get_reservation_week.id
    end

    if @reservation.save
      redirect_to @reservation, notice: 'Reservation was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /reservations/1
  def update
    if @reservation.update(reservation_params)
      redirect_to @reservation, notice: 'Reservation was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /reservations/1
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    def get_reservation_week
      if !reservation_params[:reservation_date].empty?
        resdate = reservation_params[:reservation_date]
        @res = ReservationWeek.find_by_res_date(resdate)

        if !@res
          @res = ReservationWeek.create(res_date: resdate)
        end

        @res
      end
    end

    def get_reservation_week_detail
      resdate = reservation_params[:reservation_date]
      @reservation_week = ReservationWeek.find_by_res_date(resdate)
      @reservation_week
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:reservation_date, :name, :wed, :thur, :fri, :sat, :sun, :mon, :tue, :dinner, :comment, :sex, :res_member_type, :user_id)
    end

    def require_login
      unless current_user
        redirect_to new_user_session_url
      end
    end
end

app/views/reservations/_form.html.erb
<%= simple_form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="fl">
      <div class="panel panel-default">
        <div class="panel-body">
          <div id="reportrange" class="pull-right">
            <i class="fa fa-calendar fa-lg"></i>
            <% if @reservation.reservation_date.nil? %>
               <span>Pick A Reservation Week</span> <b class="caret"></b>
            <% else %>
              <span><%= l(@reservation.reservation_date, format: :notime) %> - <%= l(@reservation.reservation_date + 7.days, format: :notime) %></span> <b class="caret"></b>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <p></p>
  <%= f.input :reservation_date, as: :hidden %>
  <%= f.input :name %>
  <div class="box panel panel-default">
    <h3> Sex </h3>
    <div class="panel panel-body">
      <%= f.collection_radio_buttons :sex, [['Male', 'Male'], ['Female', 'Female']], :first, :last, :item_wrapper_tag => :div %>
    </div>
  </div>
  <div class="box panel panel-default">
    <h3>Member Type</h3>
    <div class="panel panel-body">
      <%= f.collection_radio_buttons :res_member_type, [['Full Member', 'Full Member'], ['Associate Member', 'Associate Member'], ['Race Member', 'Race Member'], ['Guest', 'Guest']], :first, :last, :item_wrapper_tag => :div %>
    </div>
  </div>
  <div class="box panel panel-default">
    <h3> Select the days you are staying and if you want the house dinner.</h3>
    <div class="panel panel-body">
      <%= f.input_field :wed, :as => :boolean, :inline_label => 'Wednesday' %>
      <%= f.input_field :thur, :as => :boolean, :inline_label => 'Thursday' %>
      <%= f.input_field :fri, :as => :boolean, :inline_label => 'Friday' %>
      <%= f.input_field :sat, :as => :boolean, :inline_label => 'Saturday' %>
      <%= f.input_field :sun, :as => :boolean, :inline_label => 'Sunday' %>
      <%= f.input_field :mon, :as => :boolean , :inline_label => 'Monday' %>
      <%= f.input_field :tue, :as => :boolean, :inline_label => 'Tuesday' %>
      <%= f.input_field :dinner, :as => :boolean, :inline_label => 'Dinner' %>
    </div>
  </div>
  <p>
    <%= f.input :comment, as: :bootsy %>
  </p>
  <%= f.button :submit, 'Create Reservation', class: 'btn btn-primary' %>
<% end %>
<script type="text/javascript">
var a = moment().day("Wednessday").week(Number).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 6).format('MMMM D, YYYY').toString();
var b = moment().day("Wednessday").week(Number).add('days', 7).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 13).format('MMMM D, YYYY').toString();
var c = moment().day("Wednessday").week(Number).add('days', 14).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 20).format('MMMM D, YYYY').toString();
var d = moment().day("Wednessday").week(Number).add('days',21 ).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 27).format('MMMM D, YYYY').toString();
var e = moment().day("Wednessday").week(Number).add('days',28 ).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 34).format('MMMM D, YYYY').toString();
var f = moment().day("Wednessday").week(Number).add('days', 35 ).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 41).format('MMMM D, YYYY').toString();
var g = moment().day("Wednessday").week(Number).add('days', 42 ).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 48).format('MMMM D, YYYY').toString();
var h = moment().day("Wednessday").week(Number).add('days', 49 ).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 55).format('MMMM D, YYYY').toString();
var obj = {};
obj[a] = [moment().day("Wednessday").week(Number), moment().day("Wednessday").week(Number).add('days', 6)];
obj[b] = [moment().day("Wednessday").week(Number).add('days', 7), moment().day("Wednessday").week(Number).add('days', 13)];
obj[c] = [moment().day("Wednessday").week(Number).add('days', 14), moment().day("Wednessday").week(Number).add('days', 20)];
obj[d] = [moment().day("Wednessday").week(Number).add('days',21 ), moment().day("Wednessday").week(Number).add('days', 27)];
obj[e] = [moment().day("Wednessday").week(Number).add('days',28 ), moment().day("Wednessday").week(Number).add('days', 34)];
obj[f] = [moment().day("Wednessday").week(Number).add('days', 35 ), moment().day("Wednessday").week(Number).add('days', 41)];
obj[g] = [moment().day("Wednessday").week(Number).add('days', 42 ), moment().day("Wednessday").week(Number).add('days', 48)];
obj[h] = [moment().day("Wednessday").week(Number).add('days', 49 ), moment().day("Wednessday").week(Number).add('days', 55)];
$('#reportrange').daterangepicker(
    {
      ranges: obj,
      startDate: moment().subtract('days', 29),
      endDate: moment()
    },
    function(start, end) {
        $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
        $('#reservation_reservation_date').val(start.format('"YYYY/MM/DD"'));
    }
);
</script>

app/views/reservations/edit.html.erb
<h1>Edit Reservation</h1>
<div class="box panel panel-default">
   <div class="panel panel-body">
		<%= render 'form' %>
	</div>
</div>
<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<div>
  <h1>Reservations</h1>
</div>
<div id="res" class="transitions-enabled">
  <div class="box panel panel-default">
    <div class="panel panel-body">
      <div class="action">
        <%= link_to new_reservation_path do %>
          <button class="btn btn-default btn-lg" >
            <span class="glyphicon glyphicon-plus"></span> Add
          </button>
        <% end %>
      </div>
    </div>
  </div>
  <div class="box panel panel-default">
    <div class="panel panel-body">
      <div class="action">
          <%= link_to pick_reservations_path do %>
            <button class="btn btn-default btn-lg" >
              <span class="glyphicon glyphicon-pencil"></span>
              <span class="glyphicon glyphicon-trash"></span> Edit/Delete
            </button>
          <% end %>
      </div>
    </div>
  </div>
  <div class="box panel panel-default">
    <div class="panel panel-body">
      <div class="action">
        <button class="btn btn-default btn-lg" data-toggle="modal" data-target="#myModal">
          <span class="glyphicon glyphicon-search" data-toggle="modal" data-target="#myModal"></span> View
        </button>
      </div>
    </div>
  </div>
</div>

<br>
<div>
  <%= link_to 'New Reservation', new_reservation_path %>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">View Reservations</h4>
      </div>
      <%= simple_form_for @reservations, :url => lookup_reservations_path, :reservation_id => '', :method => :post do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <div class="fl">
              <div class="panel panel-default">
                <div class="panel-body">
                  <div id="reportrange" class="pull-right">
                    <i class="fa fa-calendar fa-lg"></i>
                      <span>Pick A Reservation Week</span> <b class="caret"></b>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <%= f.input :reservation_date, as: :hidden %>
        </div>
        <div class="modal-footer">
          <%= f.button :submit,  label: 'View Reservations', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<script type="text/javascript">
var a = moment().day("Wednessday").week(Number).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 6).format('MMMM D, YYYY').toString();
var b = moment().day("Wednessday").week(Number).add('days', 7).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 13).format('MMMM D, YYYY').toString();
var c = moment().day("Wednessday").week(Number).add('days', 14).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 20).format('MMMM D, YYYY').toString();
var d = moment().day("Wednessday").week(Number).add('days',21 ).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 27).format('MMMM D, YYYY').toString();
var e = moment().day("Wednessday").week(Number).add('days',28 ).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 34).format('MMMM D, YYYY').toString();
var f = moment().day("Wednessday").week(Number).add('days', 35 ).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 41).format('MMMM D, YYYY').toString();
var g = moment().day("Wednessday").week(Number).add('days', 42 ).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 48).format('MMMM D, YYYY').toString();
var h = moment().day("Wednessday").week(Number).add('days', 49 ).format('MMMM D, YYYY').toString() + ' - ' + moment().day("Wednessday").week(Number).add('days', 55).format('MMMM D, YYYY').toString();
var obj = {};
obj[a] = [moment().day("Wednessday").week(Number), moment().day("Wednessday").week(Number).add('days', 6)];
obj[b] = [moment().day("Wednessday").week(Number).add('days', 7), moment().day("Wednessday").week(Number).add('days', 13)];
obj[c] = [moment().day("Wednessday").week(Number).add('days', 14), moment().day("Wednessday").week(Number).add('days', 20)];
obj[d] = [moment().day("Wednessday").week(Number).add('days',21 ), moment().day("Wednessday").week(Number).add('days', 27)];
obj[e] = [moment().day("Wednessday").week(Number).add('days',28 ), moment().day("Wednessday").week(Number).add('days', 34)];
obj[f] = [moment().day("Wednessday").week(Number).add('days', 35 ), moment().day("Wednessday").week(Number).add('days', 41)];
obj[g] = [moment().day("Wednessday").week(Number).add('days', 42 ), moment().day("Wednessday").week(Number).add('days', 48)];
obj[h] = [moment().day("Wednessday").week(Number).add('days', 49 ), moment().day("Wednessday").week(Number).add('days', 55)];
$('#reportrange').daterangepicker(
    {
      ranges: obj,
      startDate: moment().subtract('days', 29),
      endDate: moment()
    },
    function(start, end) {
        $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
        $('#reservation_reservation_date').val(start.format('"YYYY/MM/DD"'));
    }
);
</script>

app/views/reservations/lookup.html.erb
<h1>Reservations</h1>
<div class="table-responsive">
	<h2> <%= l(@reservation_week.res_date, format: :notime) %> - <%= l(@reservation_week.res_date + 7.days, format: :notime) %> </h2>
	<% if !@reservation_week.note.blank? %>
	 <h3> <%= @reservation_week.note %> </h3>
	<% end %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Sex</th>
        <th>Type</th>
        <th>Wed</th>
        <th>Thu</th>
        <th>Fri</th>
        <th>Sat</th>
        <th>Sun</th>
        <th>Mon</th>
        <th>Tue</th>
        <th>Dinner</th>
        <th>Comment</th>
      </tr>
    </thead>

    <tbody>
      <% @reservations.each do |reservation| %>
        <tr>
          <td><%= reservation.name %></td>
          <td><%= reservation.sex.capitalize %></td>
          <td><%= reservation.res_member_type.capitalize %></td>
          <% if reservation.wed? %>
            <td> <span class="glyphicon glyphicon-ok-circle"></span></td>
          <% else %>
            <td><span class="glyphicon glyphicon-remove-circle"></span></td>
          <% end %>
          <% if reservation.thur? %>
            <td> <span class="glyphicon glyphicon-ok-circle"></span></td>
          <% else %>
            <td><span class="glyphicon glyphicon-remove-circle"></span></td>
          <% end %>
          <% if reservation.fri? %>
            <td> <span class="glyphicon glyphicon-ok-circle"></span></td>
          <% else %>
            <td><span class="glyphicon glyphicon-remove-circle"></span></td>
          <% end %>
          <% if reservation.sat? %>
            <td> <span class="glyphicon glyphicon-ok-circle"></span></td>
          <% else %>
            <td><span class="glyphicon glyphicon-remove-circle"></span></td>
          <% end %>
          <% if reservation.sun? %>
            <td> <span class="glyphicon glyphicon-ok-circle"></span></td>
          <% else %>
            <td><span class="glyphicon glyphicon-remove-circle"></span></td>
          <% end %>
          <% if reservation.mon? %>
            <td> <span class="glyphicon glyphicon-ok-circle"></span></td>
          <% else %>
            <td><span class="glyphicon glyphicon-remove-circle"></span></td>
          <% end %>
          <% if reservation.tue? %>
            <td> <span class="glyphicon glyphicon-ok-circle"></span></td>
          <% else %>
            <td><span class="glyphicon glyphicon-remove-circle"></span></td>
          <% end %>
          <% if reservation.dinner? %>
            <td> <span class="glyphicon glyphicon-ok-circle"></span></td>
          <% else %>
            <td><span class="glyphicon glyphicon-ban-circle"></span></td>
          <% end %>
          <td><%= reservation.comment.html_safe %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>
<div class="box panel panel-default">
   <div class="panel panel-body">
		<%= render 'form' %>
	</div>
</div>

<%= link_to 'Back', reservations_path %>

app/views/reservations/pick.html.erb
<div class="box panel panel-default">
  <div class="panel panel-body">
    <h1>Edit/Delete Reservations</h1>
    <div class="action">
      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Reservation Date</th>
              <th>Name</th>
              <th>Sex</th>
              <th>Type</th>
              <th>Wed</th>
              <th>Thu</th>
              <th>Fri</th>
              <th>Sat</th>
              <th>Sun</th>
              <th>Mon</th>
              <th>Tue</th>
              <th>Dinner</th>
              <th>Comment</th>
              <th></th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @reservations.each do |reservation| %>
              <tr>
                <td><%= l(reservation.reservation_date, format: :notime) %> - <%= l(reservation.reservation_date + 7.days, format: :notime) %></td>
                <td><%= reservation.name %></td>
                <td><%= reservation.sex.capitalize %></td>
                <td><%= reservation.res_member_type.capitalize %></td>
                <% if reservation.wed? %>
                  <td> <span class="glyphicon glyphicon-ok-circle"></span></td>
                <% else %>
                  <td><span class="glyphicon glyphicon-remove-circle"></span></td>
                <% end %>
                <% if reservation.thur? %>
                  <td> <span class="glyphicon glyphicon-ok-circle"></span></td>
                <% else %>
                  <td><span class="glyphicon glyphicon-remove-circle"></span></td>
                <% end %>
                <% if reservation.fri? %>
                  <td> <span class="glyphicon glyphicon-ok-circle"></span></td>
                <% else %>
                  <td><span class="glyphicon glyphicon-remove-circle"></span></td>
                <% end %>
                <% if reservation.sat? %>
                  <td> <span class="glyphicon glyphicon-ok-circle"></span></td>
                <% else %>
                  <td><span class="glyphicon glyphicon-remove-circle"></span></td>
                <% end %>
                <% if reservation.sun? %>
                  <td> <span class="glyphicon glyphicon-ok-circle"></span></td>
                <% else %>
                  <td><span class="glyphicon glyphicon-remove-circle"></span></td>
                <% end %>
                <% if reservation.mon? %>
                  <td> <span class="glyphicon glyphicon-ok-circle"></span></td>
                <% else %>
                  <td><span class="glyphicon glyphicon-remove-circle"></span></td>
                <% end %>
                <% if reservation.tue? %>
                  <td> <span class="glyphicon glyphicon-ok-circle"></span></td>
                <% else %>
                  <td><span class="glyphicon glyphicon-remove-circle"></span></td>
                <% end %>
                <% if reservation.dinner? %>
                  <td> <span class="glyphicon glyphicon-ok-circle"></span></td>
                <% else %>
                  <td><span class="glyphicon glyphicon-ban-circle"></span></td>
                <% end %>
                <td><%= reservation.comment.html_safe %></td>
                <td>
                  <%= link_to edit_reservation_path(reservation) do %>
                    <span class="glyphicon glyphicon-edit"></span> Edit
                  <% end %>
                </td>
                <td>
                  <%= link_to reservation, method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <span class="glyphicon glyphicon-trash"></span> Delete
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <br>

      <%= link_to 'New Reservation', new_reservation_path %>
    </div>
  </div>
</div>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reservation date:</strong>
  <%= @reservation.reservation_date %>
</p>

<p>
  <strong>Name:</strong>
  <%= @reservation.name %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @reservation.sex %>
</p>

<p>
  <strong>Member Type:</strong>
  <%= @reservation.res_member_type %>
</p>


<p>
  <strong>Wed:</strong>
  <%= @reservation.wed %>
</p>

<p>
  <strong>Thur:</strong>
  <%= @reservation.thur %>
</p>

<p>
  <strong>Fri:</strong>
  <%= @reservation.fri %>
</p>

<p>
  <strong>Sat:</strong>
  <%= @reservation.sat %>
</p>

<p>
  <strong>Sun:</strong>
  <%= @reservation.sun %>
</p>

<p>
  <strong>Mon:</strong>
  <%= @reservation.mon %>
</p>

<p>
  <strong>Tue:</strong>
  <%= @reservation.tue %>
</p>

<p>
  <strong>Dinner:</strong>
  <%= @reservation.dinner %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @reservation.comment %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>