config/routes.rb
Rails.application.routes.draw do
  root :to => "visitors#index"
  devise_for :users
  resources :users

  resources :reservation_weeks do
    get 'pick', on: :collection
  end

  resources :reservations do
    get 'pick', on: :collection
    post 'lookup', on: :collection
  end

  resources :pages

  get 'contact' => 'pages#contact'
  get 'guest' => 'pages#guest'
  get 'library' => 'pages#library'
  get 'membership' => 'pages#membership'
  get 'notes' =>  'pages#note'
  get 'race' => 'pages#race'
  get 'social'=> 'pages#social'
  get 'pages' => 'pages#index'

  resources :public_pins
end

app/views/layouts/_footer.html.erb
<!-- Footer Container -->
<div class="footer-wrapper">

  <!-- Footer Top Container -->
  <div class="footer-top">

    <!-- Google Map -->
    <a class="gmap-button">Locate us on map</a>
    <div class="gmap-wrapper">
      <div id="google-map-footer"></div>
    </div>
    <!-- /Google Map -->

  </div>
  <!-- /Footer Top Container -->

  <!-- Footer Bottom Container -->
  <div class="footer-bottom">

    <!-- Container -->
    <div class="container">
      <div class="row">
        <!-- Footer Menu -->
        <div class="col-md-12 col-sm-12 columns">
          <div class="menu-footer">
            <ul class="list-inline">
              <li><%= link_to 'Home', root_path %></li>
              <li><%= link_to 'Membership', membership_path %></li>
              <li><%= link_to 'Guest FAQ', guest_path %></li>
            </ul>
          </div>
        </div>
        <!-- /Footer Menu -->
        <!-- Copyright -->
        <div class="col-md-12 col-sm-12 columns">
          <div class="copyright">
            <p>Copyright © 2015 - Brettl Hupher Ski & Sports Club | All Rights Reserved</p>
          </div>
        </div>
        <!-- /Copyright -->
        <!-- Footer Social -->
        <div class="col-md-12 col-sm-12 columns">
          <div class="social-footer">
            <ul class="list-inline social-list">
              <li><a href="" class="ToolTip" title="Facebook"><span class="fa fa-facebook"></span></a></li>
              <li><a href="" class="ToolTip" title="Twitter"><span class="fa fa-twitter"></span></a></li>
              <li><a href="" class="ToolTip" title="Google+"><span class="fa fa-google-plus"></span></a></li>
              <li><a href="" class="ToolTip" title="Pinterest"><span class="fa fa-pinterest"></span></a></li>
              <li><a href="" class="ToolTip" title="Linkedin"><span class="fa fa-linkedin"></span></a></li>
            </ul>
          </div>
        </div>
        <!-- /Footer Social -->
      </div>
    </div>
    <!-- /Container -->

  </div>
  <!-- /Footer Bottom Container -->

</div>
<!-- /Footer Container -->

</div>

<!-- Back To Top -->
<a href="#page-top" class="scrollup smooth-scroll" ><span class="fa fa-angle-up"></span></a>

app/views/layouts/_main_nav.html.erb
<div class="header-main">

  <!-- Container -->
  <div class="container">

    <!-- Main Navigation & Logo -->
    <div class="main-navigation">
      <div class="row">

        <!-- Main Navigation -->
        <div class="col-md-12 columns">
          <nav class="navbar navbar-default gfx-mega nav-left" role="navigation">

            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header"> <a class="navbar-toggle" data-toggle="collapse" data-target="#gfx-collapse"></a>
              <div class="logo"> <a href="index.html"><%= image_tag 'brettllogo.png', lat: 'Logo', width: '75px' %></a> </div>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="gfx-collapse">
              <ul class="nav navbar-nav gfx-nav">
                <li>
                  <%= link_to root_path do %>
                    <div class="iconbox vertical animation fadeInLeft"> <span class="livicon" data-n="home" data-s="20" data-color="#EB2D2E" data-hovercolor="#EB2D2E" data-op="1" data-onparent="true" alt="home"></span>
                    </div>
                  <% end %>
                </li>
                <li>
                  <%= link_to 'Membership', membership_path %>
                </li>
                <li>
                  <%= link_to 'Guests FAQ', guest_path%>
                </li>
                <% if user_signed_in? %>
                  <li>
                    <%= link_to  destroy_user_session_path, :method=>'delete'  do%>
                      <div class="iconbox vertical animation fadeInLeft"> <span class="livicon" data-n="disconnect" data-s="20" data-color="#EB2D2E" data-hovercolor="#EB2D2E" data-op="1" data-onparent="true" alt="logout"></span>
                      </div>
                    <% end %>
                  </li>

                  <li class="dropdown gfx-mega-fw"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Members Area<b class="caret"></b></a>
                    <ul class="dropdown-menu nav navbar-right">
                      <li>
                        <div class="gfx-mega-content">
                          <div class="row">
                            <div class="col-lg-3 col-sm-3">
                              <ul class="mega-menu-list">
                                <li><%= link_to 'Reservations', reservations_path %></li>
                                <li><%= link_to 'Notes', notes_path %></li>
                                <li><%= link_to 'Library', library_path %></li>
                              </ul>
                            </div>
                          </div>
                        </div>
                      </li>
                    </ul>
                  </li>
                  <% if current_user.admin? %>
                    <li class="dropdown gfx-mega-fw"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Administration Area <b class="caret"></b></a>
                      <ul class="dropdown-menu nav navbar-right">
                        <li>
                          <div class="gfx-mega-content">
                            <div class="row">
                              <div class="col-lg-3 col-sm-3">
                                <ul class="mega-menu-list">
                                  <li><%= link_to 'Reservations', reservations_path %></li>
                                  <li><%= link_to 'Notes', notes_path %></li>
                                  <li><%= link_to 'Library', library_path %></li>
                                  <li><%= link_to 'Users', users_path %></li>
                                </ul>
                              </div>
                            </div>
                          </div>
                        </li>
                      </ul>
                    </li>
                  <% end %>
                <% else %>
                  <li>
                    <%= link_to new_user_session_path do %>
                      <div class="iconbox vertical animation fadeInLeft"> <span class="livicon" data-n="user" data-s="20" data-color="#EB2D2E" data-hovercolor="#EB2D2E" data-op="1" data-onparent="true"></span>
                      </div>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </div>
            <!-- /.navbar-collapse -->

          </nav>
        </div>
        <!-- /Main Navigation -->

      </div>
    </div>
    <!-- /Main Navigation & Logo -->

  </div>
  <!-- /Container -->

</div>
<!-- /Header Main Container -->

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
.header-top
  .container
    .row
      .col-md-12.colsm-12.columns
        .header-top-left
          %ul.social-top
            %li
              = link_to 'https://www.facebook.com/brettl.hupfers', class: 'Tooltip' do
                %span.fa.fa-facebook
            %li
              = link_to 'https://twitter.com/Brettl_Hupfers', class: 'Tooltip' do
                %span.fa.fa-twitter
            %li
              = link_to 'https://plus.google.com/u/0/106339247993048811475/posts', class: 'Tooltip' do
                %span.fa.fa-google-plus
            %li
              = link_to '#', class: 'Tooltip' do
                %span.fa.fa-instagram
= render 'layouts/main_nav'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<li><%= link_to 'Home', root_path, class: 'navbar-brand' %></li>
<li><%= link_to 'Membership', membership_path %> </li>
<li> <%= link_to 'Guest', guest_path%> </li>
<li> <%= link_to 'Social', social_path %></li>
<li> <%= link_to 'Race', race_path %></li>
<li> <%= link_to 'Contact Us', contact_path %></li>

<% if user_signed_in? %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Member Pages <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li> <%= link_to 'Notes', notes_path %></li>
      <li> <%= link_to 'Library', library_path %></li>
      <li> <%= link_to 'Reservations', reservations_path %></li>
    </ul>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
  <% if current_user.admin? %>
    <li><%= link_to 'Users Admin', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation_links_copy.html.erb
<%# add navigation links to this file %>

<li><%= link_to 'Home', root_path, class: 'navbar-brand' %></li>
<li><%= link_to 'Membership', membership_path %> </li>
<li> <%= link_to 'Guest', guest_path%> </li>
<li> <%= link_to 'Social', social_path %></li>
<li> <%= link_to 'Race', race_path %></li>
<li> <%= link_to 'Contact Us', contact_path %></li>

<% if user_signed_in? %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Member Pages <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li> <%= link_to 'Notes', notes_path %></li>
      <li> <%= link_to 'Library', library_path %></li>
      <li> <%= link_to 'Reservations', reservations_path %></li>
    </ul>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
  <% if current_user.admin? %>
    <li><%= link_to 'Users Admin', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_slider.html.erb
<!-- Slider Container -->

<div class="slider-wrapper">

  <!-- START REVOLUTION SLIDER 3.1 rev5 fullwidth mode -->

  <div class="tp-banner-container">
    <div class="tp-banner" >
      <ul>

        <!-- SLIDE  -->
        <li data-transition="slidehorizontal" data-slotamount="1" data-masterspeed="1000" data-fstransition="fade" data-fsmasterspeed="1000" data-fsslotamount="7" data-saveperformance="off"  data-title="The Brettl Hupfer Ski & Sports Club">
          <!-- MAIN IMAGE -->
          <%= image_tag 'slider/ski-line-up-1.jpg', alt:'slidebg1', data: {bgfit: 'cover', bgposition: 'center center', bgrepeat: 'no-repeat'} %>
          <div class="tp-caption large_bold_white customin customout tp-resizeme rs-parallaxlevel-3"
            data-x="center"
            data-y="150"

            data-splitin="words"
            data-elementdelay="0.1"
            data-start="1250"
            data-speed="1500"
            data-easing="Power3.easeOut"
            data-customin="x:0;y:-20;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"

            data-splitout="lines"
            data-endelementdelay="0"
            data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:10;scaleY:10;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
            data-endspeed="1500"
            data-endeasing="Power3.easeInOut"
            data-captionhidden="on"
            style="font-size:90px;line-height:110px;">The Brettl Hupfer Ski & Sports Club</div>
          <div class="tp-caption mediumlarge_light_white script-font customin customout tp-resizeme rs-parallaxlevel-4"
            data-x="center"
            data-y="280"

            data-splitin="words"
            data-elementdelay="0.05"
            data-start="1650"
            data-speed="900"
            data-easing="Back.easeOut"
            data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
            data-endelementdelay="0.1"
            data-customout="x:-230;y:-20;z:0;rotationX:0;rotationY:0;rotationZ:90;scaleX:0.2;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%"
            data-endspeed="500"
            data-endeasing="Back.easeIn"
            data-captionhidden="on"
            style="z-index: 4; font-size:52px;">We Love the Outdoors! </div>
          <div class="tp-caption sfb rs-parallaxlevel-5"
            data-x="center"
            data-y="380"
            data-speed="800"
            data-start="2600"
            data-easing="Power4.easeOut"
            data-endspeed="300"
            data-endeasing="Power1.easeIn"
            data-captionhidden="off"
            style="z-index: 6"> <a href="#services" class="btn btn-primary btn-lg">Join Us! <i class="fa fa-angle-double-down iconright"></i></a> </div>
        </li>

        <!-- SLIDE  -->
        <li data-transition="slidehorizontal" data-slotamount="1" data-masterspeed="1000" data-fstransition="fade" data-fsmasterspeed="1000" data-fsslotamount="7" data-saveperformance="off"  data-title="Get Into It!">
          <!-- MAIN IMAGE -->
          <%= image_tag 'slider/snowshoe-2.jpg', alt:'slidebg2', data: {bgfit: 'cover', bgposition: 'center center', bgrepeat: 'no-repeat'} %>
          <div class="tp-caption large_bold_white customin customout rs-parallaxlevel-3"
            data-x="center"
            data-y="150"

            data-splitin="chars"
            data-elementdelay="0.1"
            data-start="1250"
            data-speed="900"
            data-easing="Power3.easeOut"
            data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:6;scaleY:6;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"

            data-splitout="lines"
            data-endelementdelay="0"
            data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:10;scaleY:10;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
            data-endspeed="1500"
            data-endeasing="Power3.easeInOut"
            data-captionhidden="on"
            style="font-size:90px;line-height:110px;">Get Into It! </div>
          <div class="tp-caption mediumlarge_light_white script-font customin customout rs-parallaxlevel-4"
            data-x="center"
            data-y="280"

            data-elementdelay="0.05"
            data-start="1650"
            data-speed="900"
            data-easing="Back.easeOut"
            data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:1;transformPerspective:300;transformOrigin:50% 0%;"
            data-endelementdelay="0.1"
            data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
            data-endspeed="500"
            data-endeasing="Back.easeIn"
            data-captionhidden="on"
            style="z-index: 4; font-size:52px;">For proper Viewing, Take Red Pill Now! </div>
          <div class="tp-caption sfb rs-parallaxlevel-5"
            data-x="center"
            data-y="380"
            data-speed="800"
            data-start="2600"
            data-easing="Power4.easeOut"
            data-endspeed="300"
            data-endeasing="Power1.easeIn"
            data-captionhidden="off"
            style="z-index: 6"> <a href="#services" class="btn btn-white btn-lg btn-alt">Take Pill! <i class="fa fa-angle-double-down iconright"></i></a> </div>
        </li>
        <!-- SLIDE  -->

        <!-- SLIDE  -->
        <li data-transition="slidehorizontal" data-slotamount="1" data-masterspeed="1000" data-fstransition="fade" data-fsmasterspeed="1000" data-fsslotamount="7" data-saveperformance="off"  data-title="Get Into It!">
          <!-- MAIN IMAGE -->
          <%= image_tag 'slider/vball-3.jpg', alt:'slidebg2', data: {bgfit: 'cover', bgposition: 'center center', bgrepeat: 'no-repeat'} %>
          <div class="tp-caption large_bold_white customin customout rs-parallaxlevel-3"
            data-x="center"
            data-y="150"

            data-splitin="chars"
            data-elementdelay="0.1"
            data-start="1250"
            data-speed="900"
            data-easing="Power3.easeOut"
            data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:6;scaleY:6;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"

            data-splitout="lines"
            data-endelementdelay="0"
            data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:10;scaleY:10;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
            data-endspeed="1500"
            data-endeasing="Power3.easeInOut"
            data-captionhidden="on"
            style="font-size:90px;line-height:110px;">Get Into It! </div>
          <div class="tp-caption mediumlarge_light_white script-font customin customout rs-parallaxlevel-4"
            data-x="center"
            data-y="280"

            data-elementdelay="0.05"
            data-start="1650"
            data-speed="900"
            data-easing="Back.easeOut"
            data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:1;transformPerspective:300;transformOrigin:50% 0%;"
            data-endelementdelay="0.1"
            data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
            data-endspeed="500"
            data-endeasing="Back.easeIn"
            data-captionhidden="on"
            style="z-index: 4; font-size:52px;">For proper Viewing, Take Red Pill Now! </div>
          <div class="tp-caption sfb rs-parallaxlevel-5"
            data-x="center"
            data-y="380"
            data-speed="800"
            data-start="2600"
            data-easing="Power4.easeOut"
            data-endspeed="300"
            data-endeasing="Power1.easeIn"
            data-captionhidden="off"
            style="z-index: 6"> <a href="#services" class="btn btn-white btn-lg btn-alt">Take Pill! <i class="fa fa-angle-double-down iconright"></i></a> </div>
        </li>
        <!-- SLIDE  -->



        <div class="tp-bannertimer tp-bottom"></div>
      </ul>
    </div>
  </div>

  <!-- END REVOLUTION SLIDER -->

</div>
<!-- /Slider Container -->

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"}
    %title= content_for?(:title) ? yield(:title) : 'Bhsc Pundit'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Bhsc Pundit'}"}
    = stylesheet_link_tag 'application', media: 'all'
    %link{rel: 'stylesheet', type: 'text/css', href: 'http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css'}
    %link{rel: 'stylesheet', type: 'text/css', href: 'http://fonts.googleapis.com/css?family=Raleway:400,200,300,100,500,600,700,800,900'}
    %link{rel: 'stylesheet', type: 'text/css', href: 'http://fonts.googleapis.com/css?family=Playball'}
  %body.bg-pattern1{data: {spy: 'scroll', target: '.navbar'}}
    .preloader
    #page-top.page-wrapper
      .header-wrapper
        = render 'layouts/navigation'
      = yield
      .footer-wrapper
        = render 'layouts/footer'


    = javascript_include_tag 'application'
    = javascript_include_tag 'http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js'
    = javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyBPrJPTDtXicdeG3LGw0TPHvmTREZ8IxUo&sensor=false'